<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>Stardew.Wasm.mm</AssemblyName>
		<LangVersion>12</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mono.Cecil" Version="0.11.6" />
		<!-- ProjectReference Include="..\MonoMod\src\MonoMod.Patcher\MonoMod.Patcher.csproj" / -->
		<ProjectReference Include="..\FNA\FNA.Core.csproj" />
		<PackageReference Include="DnsOverHttps" Version="1.2.2" />
	</ItemGroup>
</Project>
